spring:
  application:
      name: Sms
  
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: sms-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.type.default.SmsMessage: com.project.sms.entity.SmsMessage

      listener:
        # 비어 있는 경우, 모든 예외는 DLQ 처리기로 전달됩니다.
        ack-mode: record 
        # 재시도 횟수 설정 (예: 최대 3번 재시도)
        retry:
          max-attempts: 3
          back-off:
            interval: 5000 # 5초 간격으로 재시도 (필요에 따라 설정)


kakao:
  client-id: YOUR_REST_API_KEY
  # 필수 아님
  client-secret: YOUR_CLIENT_SECRET
  redirect-uri: "http://localhost:8080/kakao/callback"

  biz-message:
    host: https://kapi.kakao.com
    access-token-url: https://kauth.kakao.com/oauth/token
    app-key: YOUR_APP_KEY

    client-secret: YOUR_CLIENT_SECRET

    template-code: YOUR_ALIMTALK_TEMPLATE_CODE # ⭐ 사전에 등록한 템플릿 코드


